import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "@fontsource/itim"; // Defaults to weight 400


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamboa Acao",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="font-itim">
        <section className="lg:mx-20">
          <Header />
        </section>
        {children}
        <Footer />
      </body>
    </html>
  );
}
